import os
import json

labs_data = {
    "01": {"session": "1", "source_status": "OFFICIAL SOURCE LAB", "doc_status": "SOURCE-DERIVED", "objective": "Build the foundational Service Discovery and Centralized Configuration infrastructure, and connect the first microservice.", "problem": "Hardcoded IPs make microservices brittle. Distributed configurations lead to configuration drift.", "arch_before": "Empty repository.", "arch_after": "Config Server (:8888), Eureka Server (:8761), and Product Service (:8081) communicating with each other.", "concepts": "Service Registry Pattern, Centralized Configuration (12-Factor App III), Spring Cloud Netflix Eureka.", "prereq": "Java 21, Maven.", "tasks": "1. Initialize config-server.\n2. Initialize eureka-server.\n3. Initialize product-service.\n4. Connect product-service to both servers.", "config": "`eureka.client.register-with-eureka=false` (server)\n`spring.config.import=optional:configserver:...`", "files": "`config-server`, `eureka-server`, `product-service`", "acceptance": "Eureka dashboard shows `PRODUCT-SERVICE` as `UP`.", "verify": "Run all three applications. Hit `http://localhost:8761`.", "expect": "Product service registers successfully.", "failures": "Config server not running before product service starts; port conflicts.", "troubleshoot": "Ensure Config Server starts first. Check `optional:` prefix in application.yml.", "arch_impact": "Establishes the foundation for all future service discovery.", "relation": "First foundational lab. Sets up routing for Session 2 (Lab 2A).", "evidence": "Official document `session-01-lab-01.md`.", "commit": "session-01: add-product-service-eureka-config"},
    "02a": {"session": "2", "source_status": "OFFICIAL SOURCE LAB", "doc_status": "SOURCE-DERIVED", "objective": "Implement Spring Cloud Gateway for dynamic routing.", "problem": "Clients shouldn't need to know the IPs or ports of individual microservices.", "arch_before": "Direct connections to product-service.", "arch_after": "API Gateway acts as the single entrypoint and routes to product-service via Eureka `lb://`.", "concepts": "API Gateway Pattern, Route Predicates, Filters, Load Balancing.", "prereq": "Lab 01.", "tasks": "1. Initialize api-gateway.\n2. Configure Eureka client.\n3. Configure route to product-service.", "config": "`spring.cloud.gateway.routes`, `lb://PRODUCT-SERVICE`.", "files": "`api-gateway/src/main/resources/application.yml`", "acceptance": "Gateway routes `/api/products/**` to `product-service`.", "verify": "Hit `http://localhost:8080/api/products`.", "expect": "200 OK from Product Service, routed via Gateway.", "failures": "Route 404s due to missing `StripPrefix`.", "troubleshoot": "Check Eureka dashboard to ensure Gateway and Product are both registered.", "arch_impact": "Hides internal network topology from clients.", "relation": "Builds on Lab 1. Prepared for Security in Lab 2B.", "evidence": "Official document `session-02-lab-02.md`.", "commit": "session-02: add-api-gateway"},
    "02b": {"session": "3", "source_status": "OFFICIAL SOURCE LAB", "doc_status": "SOURCE-DERIVED", "objective": "Secure the Gateway with JWT and add Redis rate limiting.", "problem": "APIs are exposed without authentication and vulnerable to DoS attacks.", "arch_before": "Open, unprotected Gateway.", "arch_after": "Gateway with `JwtAuthFilter` and Redis Token-Bucket `RequestRateLimiter`.", "concepts": "JWT structure, Global/Route Filters, Token-Bucket Rate Limiting.", "prereq": "Lab 02A, Redis.", "tasks": "1. Add jjwt.\n2. Implement JwtAuthFilter.\n3. Add Redis RequestRateLimiter config.", "config": "`spring.cloud.gateway.default-filters`, `redis-rate-limiter.replenishRate`.", "files": "`api-gateway/.../JwtAuthFilter.java`", "acceptance": "Unauthenticated requests yield 401; excessive requests yield 429.", "verify": "Send request without Authorization header.", "expect": "401 Unauthorized.", "failures": "Redis connection refused; JWT signature mismatch.", "troubleshoot": "Ensure Redis is running. Check JWT secret consistency.", "arch_impact": "Moves security to the edge.", "relation": "Builds on Lab 2A. Security logic later migrated to OAuth2 in Session 20.", "evidence": "Official document `session-03-lab-2b.md`.", "commit": "session-03: add-jwt-auth-and-rate-limiting"},
    "03a": {"session": "4", "source_status": "OFFICIAL SOURCE LAB", "doc_status": "SOURCE-DERIVED", "objective": "Scaffold Order and Payment services; apply Circuit Breaker and Retry.", "problem": "Synchronous inter-service calls fail cascadingly when downstream services crash.", "arch_before": "No inter-service resilience.", "arch_after": "Order Service protected by Resilience4j Circuit Breaker against Payment Service failures.", "concepts": "Circuit Breaker states (Closed, Open, Half-Open), Exponential Backoff Retry.", "prereq": "Lab 02B.", "tasks": "1. Scaffold services.\n2. Add Resilience4j dependency.\n3. Add @CircuitBreaker and @Retry.", "config": "`resilience4j.circuitbreaker.instances.*`", "files": "`order-service`, `payment-service`", "acceptance": "Order service invokes fallback method when payment service is down.", "verify": "Stop payment-service and hit order creation.", "expect": "Fallback response triggered immediately without waiting for standard HTTP timeout.", "failures": "Fallback method signature mismatch (must match original method + Throwable).", "troubleshoot": "Check Actuator `/actuator/health` to see Circuit Breaker state.", "arch_impact": "Introduces fault tolerance.", "relation": "First resilience lab. Followed by Bulkhead in Lab 3B.", "evidence": "Official document `session-04-lab-3a.md`.", "commit": "session-04: add-order-payment-and-circuit-breaker"},
    "03b": {"session": "5", "source_status": "OFFICIAL SOURCE LAB", "doc_status": "SOURCE-DERIVED", "objective": "Add Bulkhead and TimeLimiter to isolate thread exhaustion.", "problem": "Slow downstream services cause upstream thread pools to fill up, hanging the entire application.", "arch_before": "Order service vulnerable to thread exhaustion if Payment service is slow but not throwing errors.", "arch_after": "Order service limits concurrent calls (Bulkhead) and enforces strict async timeouts (TimeLimiter).", "concepts": "Semaphore Bulkhead, ThreadPool Bulkhead, TimeLimiter, Async execution.", "prereq": "Lab 03A.", "tasks": "1. Add @Bulkhead.\n2. Add @TimeLimiter.\n3. Return CompletableFuture.", "config": "`resilience4j.timelimiter.instances.*`, `resilience4j.bulkhead.instances.*`", "files": "`order-service/.../PaymentClient.java`", "acceptance": "Calls exceeding timeout immediately trigger fallback; concurrent calls are capped.", "verify": "Add `Thread.sleep` to payment service.", "expect": "TimeLimiter triggers fallback after configured duration.", "failures": "TimeLimiter without CompletableFuture return type fails at runtime.", "troubleshoot": "Ensure method returns `CompletableFuture` and class is proxied by Spring.", "arch_impact": "Prevents cascading resource exhaustion.", "relation": "Completes Resilience4j stack for Order Service.", "evidence": "Official document `session-05-lab-3b.md`.", "commit": "session-05: add-bulkhead-and-timelimiter"},
    "04a": {"session": "6", "source_status": "OFFICIAL SOURCE LAB", "doc_status": "SOURCE-DERIVED", "objective": "Build Inventory Service and implement sync communication via OpenFeign.", "problem": "Manual RestTemplate calls are verbose and hard to maintain.", "arch_before": "Hardcoded RestTemplate or WebClient usage.", "arch_after": "Declarative Feign interfaces used for synchronous inter-service communication.", "concepts": "Spring Cloud OpenFeign, ErrorDecoder, Declarative REST Clients.", "prereq": "Lab 03B.", "tasks": "1. Scaffold inventory-service.\n2. Create Feign client in order-service.\n3. Map Feign exceptions.", "config": "`@EnableFeignClients`, `spring.cloud.openfeign.client.config.*`", "files": "`inventory-service`, `order-service`", "acceptance": "Order service seamlessly fetches stock from inventory via Feign.", "verify": "Place order requiring stock check.", "expect": "Successful stock validation across service boundaries.", "failures": "Feign URL mapping errors; unhandled FeignExceptions.", "troubleshoot": "Verify Eureka registration. Implement Custom ErrorDecoder to unwrap exceptions.", "arch_impact": "Standardizes synchronous HTTP calls.", "relation": "Prepares the sync baseline before Kafka async is introduced in Session 7.", "evidence": "Official document missing locally; reconstructed from curriculum map and reference implementation.", "commit": "session-06: add-inventory-and-feign-clients"},
    "05a": {"session": "7", "source_status": "OFFICIAL SOURCE LAB", "doc_status": "RECONSTRUCTED", "objective": "Implement an Event-Driven Choreography Saga.", "problem": "Distributed transactions spanning multiple databases cannot use traditional ACID COMMIT/ROLLBACK.", "arch_before": "Synchronous HTTP calls acting as pseudo-transactions.", "arch_after": "Asynchronous Kafka events drive state changes across Order, Inventory, and Payment.", "concepts": "Saga Pattern, Choreography, Event-Driven Architecture, Kafka Topics/Consumers.", "prereq": "Lab 04A, Kafka cluster.", "tasks": "1. Deploy Kafka.\n2. Produce `OrderCreatedEvent`.\n3. Consume in Inventory/Payment.\n4. Produce success/failure events to complete or compensate.", "config": "`spring.kafka.bootstrap-servers`, consumer group IDs.", "files": "`docker-compose.yml`, `order`, `inventory`, `payment` event listeners", "acceptance": "Order flows from PENDING to COMPLETED (or CANCELLED) via Kafka events.", "verify": "Place an order; watch logs for Kafka message consumption.", "expect": "Eventual consistency achieved across 3 databases.", "failures": "Serialization errors; incorrect topic names; consumer group conflicts.", "troubleshoot": "Ensure `JsonSerializer`/`JsonDeserializer` is configured. Check Kafka tool/logs.", "arch_impact": "Removes temporal coupling but introduces eventual consistency complexity.", "relation": "Crucial pattern. Later refactored to Orchestration in Session 12.", "evidence": "Official document exists (`session-07-lab-5a.md`) but is empty. Reconstructed from reference implementation and S07 deck.", "commit": "session-07: add-kafka-and-choreography-saga"},
    "06a": {"session": "8", "source_status": "OFFICIAL SOURCE LAB", "doc_status": "SOURCE-DERIVED", "objective": "Add PostgreSQL persistence and Redis Cache-Aside to Product Service.", "problem": "In-memory stores lose data on restart. Repeated DB reads for static products degrade performance.", "arch_before": "In-memory lists inside service classes.", "arch_after": "Postgres JPA repository with `@Cacheable` Redis layer in front.", "concepts": "Spring Data JPA, Cache-Aside Pattern, Cache Eviction.", "prereq": "Lab 05A.", "tasks": "1. Configure Postgres.\n2. Migrate Product to JPA Entity.\n3. Add `@EnableCaching`.\n4. Annotate methods.", "config": "`spring.datasource.url`, `spring.cache.type=redis`.", "files": "`product-service` Entity, Repository, Service classes.", "acceptance": "Products persist across restarts. Fetching same product twice hits Redis.", "verify": "Restart service, data remains. Check Redis CLI `KEYS *`.", "expect": "Fast reads from Redis, writes update Postgres and evict cache.", "failures": "Object serialization failures in Redis.", "troubleshoot": "Ensure Product entity implements `Serializable` or configure JSON serializer for RedisTemplate.", "arch_impact": "Establishes standard data layer.", "relation": "Closes out Phase 1 foundation.", "evidence": "Official document `session-08-lab-6a.md`.", "commit": "session-08: add-postgres-and-redis-caching"},
    "08a": {"session": "9", "source_status": "NO STANDALONE SOURCE LAB", "doc_status": "RECONSTRUCTED", "objective": "Containerize the platform using Docker multi-stage builds.", "problem": "Inconsistent environments between dev and prod ('It works on my machine').", "arch_before": "Services run manually via `mvn spring-boot:run`.", "arch_after": "All 7 services packaged into Docker images and orchestrated via Docker Compose.", "concepts": "Multi-stage Dockerfiles, Docker Compose networking.", "prereq": "Phase 1 completion.", "tasks": "1. Write Dockerfile for each service.\n2. Update docker-compose.yml to include app services.", "config": "`docker-compose.yml` networks, environment variables.", "files": "`Dockerfile` (in every service), root `docker-compose.yml`", "acceptance": "`docker compose up` brings up the entire platform successfully.", "verify": "Run `docker compose up -d`.", "expect": "All containers healthy and inter-communicating via Docker DNS.", "failures": "Services fail to start because Config/Eureka are not ready.", "troubleshoot": "Use `depends_on: condition: service_healthy` in compose.", "arch_impact": "Standardizes deployment artifact.", "relation": "Prerequisite for K8s deployment in Session 15.", "evidence": "Reconstructed from reference implementation, git history, and S09 deck.", "commit": "session-09: add-multi-stage-dockerfiles"},
    "09a": {"session": "10", "source_status": "NO STANDALONE SOURCE LAB", "doc_status": "RECONSTRUCTED", "objective": "Implement Spring Boot integration tests with Testcontainers.", "problem": "Mocking databases hides actual SQL and serialization errors.", "arch_before": "Unit tests only.", "arch_after": "Integration tests spin up real Postgres/Redis containers during the test phase.", "concepts": "Test Pyramid, Testcontainers, `@WebMvcTest`, `@SpringBootTest`.", "prereq": "Lab 08A.", "tasks": "1. Add Testcontainers dependencies.\n2. Write ProductService integration tests.", "config": "`@Testcontainers`, `@Container`.", "files": "`product-service/src/test/...`", "acceptance": "`mvn test` spins up Docker containers, runs tests against them, and tears them down.", "verify": "Run `mvn clean test` on product-service.", "expect": "Tests pass against a real ephemeral Postgres instance.", "failures": "Docker daemon not running; port conflicts.", "troubleshoot": "Ensure Docker Desktop is running before Maven.", "arch_impact": "Increases confidence in data layer.", "relation": "Part 1 of Testing phase. Followed by Contract Testing.", "evidence": "Reconstructed from reference implementation and S10 deck.", "commit": "session-10: add-testcontainers-integration-tests"},
    "09b": {"session": "11", "source_status": "NO STANDALONE SOURCE LAB", "doc_status": "RECONSTRUCTED", "objective": "Implement Contract Testing (Pact) and Chaos Testing (WireMock).", "problem": "Microservices break when downstream APIs change formats unexpectedly.", "arch_before": "Assumed API compatibility.", "arch_after": "Consumer-Driven Contracts ensure upstream providers don't break downstream consumers.", "concepts": "Consumer-Driven Contracts, Pact, WireMock Fault Injection.", "prereq": "Lab 09A.", "tasks": "1. Write Pact consumer test in order-service.\n2. Write Pact provider verification in inventory-service.\n3. Use WireMock to simulate HTTP 500s.", "config": "Pact maven plugin, `@PactFolder`.", "files": "`order-service` tests, `inventory-service` tests", "acceptance": "Pact file generated and verified successfully.", "verify": "Run `mvn test` in both services.", "expect": "Contracts verified.", "failures": "State setup mismatch (`@State`).", "troubleshoot": "Ensure provider state methods correctly mock the required DB state.", "arch_impact": "Prevents integration regressions.", "relation": "Completes Testing phase.", "evidence": "Reconstructed from reference implementation and S11 deck.", "commit": "session-11: add-pact-and-wiremock-tests"},
    "10a": {"session": "12", "source_status": "NO STANDALONE SOURCE LAB", "doc_status": "RECONSTRUCTED", "objective": "Migrate from Choreography to Orchestration Saga.", "problem": "Choreography becomes impossible to trace and maintain as the number of services grows.", "arch_before": "Peer-to-peer event listening (Choreography).", "arch_after": "Order Service acts as the centralized Orchestrator (State Machine) dispatching commands.", "concepts": "Orchestration Saga, State Machine, Command/Reply Messaging.", "prereq": "Lab 09B.", "tasks": "1. Add Orchestrator to order-service.\n2. Change Payment/Inventory to listen for Commands and emit Replies.", "config": "State machine state transitions.", "files": "`order-service` saga package.", "acceptance": "Orders flow through the Orchestrator state machine successfully.", "verify": "Place order and observe state machine logs.", "expect": "Centralized control flow.", "failures": "Deadlocks; missing reply topics.", "troubleshoot": "Ensure every command has exactly one correlating reply.", "arch_impact": "Shifts complexity from network back to the orchestrator service.", "relation": "Major architectural refactoring of Lab 05A.", "evidence": "Reconstructed from reference implementation and S12 deck.", "commit": "session-12: migrate-to-saga-orchestration"},
    "11a": {"session": "13", "source_status": "NO STANDALONE SOURCE LAB", "doc_status": "RECONSTRUCTED", "objective": "Implement GitHub Actions CI/CD and build Notification Service.", "problem": "Manual builds are error-prone; failed events disappear into the void.", "arch_before": "Manual `mvn package`.", "arch_after": "Automated pipeline; Notification Service uses `@RetryableTopic` and DLQ.", "concepts": "CI/CD Pipelines, Kafka Dead Letter Queue (DLQ), @RetryableTopic.", "prereq": "Lab 10A.", "tasks": "1. Write `.github/workflows/build.yml`.\n2. Build `notification-service` with DLQ.", "config": "`@RetryableTopic(attempts = 3)`.", "files": "`.github/workflows`, `notification-service`", "acceptance": "Pipeline passes on commit; Notification service routes failures to DLQ.", "verify": "Push to branch; trigger Kafka failure in notification.", "expect": "Event lands in `notification-events-dlt`.", "failures": "Pipeline YAML syntax errors.", "troubleshoot": "Use GitHub Actions UI to trace pipeline steps.", "arch_impact": "Automates verification; adds event failure safety net.", "relation": "Prepares CD flow for GitOps.", "evidence": "Reconstructed from reference implementation and S13 deck.", "commit": "session-13: add-ci-pipeline-and-notification-service"},
    "11b": {"session": "14", "source_status": "NO STANDALONE SOURCE LAB", "doc_status": "RECONSTRUCTED", "objective": "Implement ArgoCD for GitOps deployment.", "problem": "Manual `kubectl apply` leads to configuration drift between cluster and git.", "arch_before": "Push-based or manual deployments.", "arch_after": "ArgoCD continuously syncs cluster state with Git.", "concepts": "GitOps, ArgoCD Application CRD.", "prereq": "Lab 11A.", "tasks": "1. Create ArgoCD manifest for product-service.", "config": "`Application` spec pointing to repo URL.", "files": "`k8s/argocd/`", "acceptance": "ArgoCD detects changes in Git and syncs to cluster.", "verify": "Apply ArgoCD app, check UI.", "expect": "Sync status: Synced.", "failures": "ArgoCD cannot reach private GitHub repo.", "troubleshoot": "Check repository credentials in ArgoCD.", "arch_impact": "Changes deployment paradigm to Pull-based.", "relation": "Follows CI pipeline.", "evidence": "Reconstructed from reference implementation and S14 deck.", "commit": "session-14: add-argocd-gitops-manifests"},
    "12a": {"session": "15", "source_status": "NO STANDALONE SOURCE LAB", "doc_status": "RECONSTRUCTED", "objective": "Write core Kubernetes manifests (Deployment, Service).", "problem": "Docker Compose does not provide self-healing or cluster orchestration.", "arch_before": "Docker Compose.", "arch_after": "Kubernetes cluster running product-service.", "concepts": "Pods, Deployments, Services, Liveness/Readiness Probes.", "prereq": "Lab 11B.", "tasks": "1. Write `deployment.yaml`.\n2. Write `service.yaml`.\n3. Add actuator probes.", "config": "`livenessProbe`, `readinessProbe` paths.", "files": "`k8s/manifests/`", "acceptance": "Pod schedules and reports healthy via Readiness probe.", "verify": "`kubectl get pods -w`.", "expect": "Pod reaches `1/1 Running`.", "failures": "CrashLoopBackOff due to missing DB.", "troubleshoot": "`kubectl describe pod` to view probe failures.", "arch_impact": "Moves platform to enterprise container orchestration.", "relation": "First K8s lab. Prepares for Helm.", "evidence": "Reconstructed from reference implementation and S15 deck.", "commit": "session-15: add-kubernetes-core-manifests"},
    "12b": {"session": "16", "source_status": "NO STANDALONE SOURCE LAB", "doc_status": "RECONSTRUCTED", "objective": "Implement Helm charts, HPA, and RBAC.", "problem": "Raw YAML files are hard to template. Manual scaling cannot handle sudden load spikes.", "arch_before": "Static replicas in raw YAML.", "arch_after": "Templated Helm chart with Horizontal Pod Autoscaling based on CPU.", "concepts": "Helm, HPA, RBAC (ServiceAccounts, Roles).", "prereq": "Lab 12A.", "tasks": "1. Create Helm chart.\n2. Add HPA resource.\n3. Configure RBAC.", "config": "`targetCPUUtilizationPercentage`.", "files": "`k8s/helm/`", "acceptance": "HPA dynamically creates pods when CPU spikes.", "verify": "`helm install`, run load generator, `kubectl get hpa`.", "expect": "Replica count increases under load.", "failures": "Metrics server not installed (HPA shows `<unknown>/50%`).", "troubleshoot": "Ensure K8s cluster has metrics-server enabled.", "arch_impact": "Enables dynamic elasticity and secure templating.", "relation": "Completes K8s phase.", "evidence": "Reconstructed from reference implementation and S16 deck.", "commit": "session-16: add-helm-hpa-and-rbac"},
    "13": {"session": "17", "source_status": "NO STANDALONE SOURCE LAB", "doc_status": "RECONSTRUCTED", "objective": "Integrate the Observability Stack (Tracing, Metrics, Logging).", "problem": "Cannot trace a request across 4 different microservices.", "arch_before": "Scattered logs in different containers.", "arch_after": "Micrometer tracing propagates Trace IDs; Zipkin aggregates them.", "concepts": "Distributed Tracing, Span ID, Trace ID, Prometheus Metrics.", "prereq": "Phase 2 completion.", "tasks": "1. Add Micrometer/Zipkin dependencies.\n2. Configure sampling rate.", "config": "`management.tracing.sampling.probability=1.0`.", "files": "All `pom.xml`, `application.yml`", "acceptance": "Single request to Gateway appears as a unified trace graph in Zipkin.", "verify": "Send request; open Zipkin UI `:9411`.", "expect": "Trace showing Gateway -> Order -> Inventory.", "failures": "Missing B3 headers; broken context propagation in async/feign calls.", "troubleshoot": "Ensure Feign/Kafka are instrumented to pass headers.", "arch_impact": "Provides critical production visibility.", "relation": "First lab of Phase 3.", "evidence": "Reconstructed from reference implementation and S17 deck.", "commit": "session-17: add-observability-zipkin-micrometer"},
    "14": {"session": "18", "source_status": "NO STANDALONE SOURCE LAB", "doc_status": "RECONSTRUCTED", "objective": "Implement CQRS (Command Query Responsibility Segregation).", "problem": "Read-heavy traffic locks the database while write-heavy operations occur.", "arch_before": "Single service model for reads and writes.", "arch_after": "Product service split into Command paths (writes) and Query paths (reads projections).", "concepts": "CQRS, Read Projections.", "prereq": "Lab 13.", "tasks": "1. Refactor product-service to use separate Command/Query objects.", "config": "Package structure changes.", "files": "`product-service`", "acceptance": "Code cleanly separates read and write operations.", "verify": "Inspect code structure.", "expect": "CQRS enforced at class/package level.", "failures": "Eventual consistency lag between write and read DBs (if separated).", "troubleshoot": "Verify synchronization mechanism.", "arch_impact": "Prepares architecture for event sourcing and massive read scaling.", "relation": "Advanced design pattern.", "evidence": "Reconstructed from reference implementation and S18 deck.", "commit": "session-18: implement-cqrs-pattern"},
    "15": {"session": "19", "source_status": "NO STANDALONE SOURCE LAB", "doc_status": "RECONSTRUCTED", "objective": "Deploy and configure Keycloak as an Identity Provider.", "problem": "Custom JWT generation is insecure and difficult to rotate.", "arch_before": "Custom `jwt-generator` tool.", "arch_after": "Keycloak provides standard OAuth2 / OIDC token issuance.", "concepts": "Identity Provider, OAuth2, OpenID Connect.", "prereq": "Lab 14.", "tasks": "1. Run Keycloak in Compose.\n2. Create Realm, Client, User, Role.", "config": "Keycloak realm export JSON.", "files": "`docker-compose.yml`, `keycloak-realm.json`", "acceptance": "Can fetch a JWT from Keycloak token endpoint.", "verify": "cURL Keycloak `/protocol/openid-connect/token`.", "expect": "Valid JWT token returned.", "failures": "Keycloak admin console inaccessible.", "troubleshoot": "Check port 8180 mapping.", "arch_impact": "Offloads identity management to an enterprise IdP.", "relation": "Prepares for Lab 16 Gateway integration.", "evidence": "Reconstructed from reference implementation and S19 deck.", "commit": "session-19: add-keycloak-realm-client-and-manual-oauth2-flow"},
    "16": {"session": "20", "source_status": "NO STANDALONE SOURCE LAB", "doc_status": "RECONSTRUCTED", "objective": "Migrate Gateway to OAuth2 Resource Server.", "problem": "Custom `JwtAuthFilter` must be manually maintained.", "arch_before": "Custom `JwtAuthFilter` parsing tokens.", "arch_after": "Spring Security OAuth2 Resource Server validates tokens via Keycloak JWKS.", "concepts": "OAuth2 Resource Server, JWKS, Role-Based Access Control.", "prereq": "Lab 15.", "tasks": "1. Remove JwtAuthFilter.\n2. Add `spring-boot-starter-oauth2-resource-server`.\n3. Configure JWKS URI.", "config": "`spring.security.oauth2.resourceserver.jwt.issuer-uri`", "files": "`api-gateway`", "acceptance": "Gateway automatically validates Keycloak tokens.", "verify": "Send request with Keycloak token.", "expect": "200 OK.", "failures": "Issuer mismatch; missing ROLE_ prefix in authorities mapping.", "troubleshoot": "Ensure custom JwtAuthenticationConverter maps Keycloak realm roles correctly.", "arch_impact": "Standardizes security.", "relation": "Replaces Lab 02B security.", "evidence": "Reconstructed from reference implementation and S20 deck.", "commit": "session-20: retire-jwtauthfilter-add-oauth2-resource-server"},
    "17": {"session": "21", "source_status": "NO STANDALONE SOURCE LAB", "doc_status": "RECONSTRUCTED", "objective": "Enable Istio Service Mesh with mTLS.", "problem": "Traffic between microservices in K8s is unencrypted and hard to route dynamically.", "arch_before": "Standard K8s services.", "arch_after": "Istio Envoy sidecars intercept all traffic; mTLS enforced.", "concepts": "Service Mesh, Sidecar Pattern, mTLS, Traffic Split/Canary.", "prereq": "Lab 16, K8s cluster.", "tasks": "1. Label namespace for injection.\n2. Apply PeerAuthentication STRICT.\n3. Apply VirtualService for 80/20 split.", "config": "`istio-injection=enabled`.", "files": "`k8s/istio/`", "acceptance": "mTLS enforced between pods.", "verify": "Curl from un-injected pod to injected pod.", "expect": "Connection refused (mTLS enforcement).", "failures": "Sidecars not injected.", "troubleshoot": "Ensure namespace label exists before pods are created.", "arch_impact": "Offloads networking and security to the infrastructure layer.", "relation": "Advanced K8s networking.", "evidence": "Reconstructed from reference implementation and S21 deck.", "commit": "session-21: add-istio-mtls-and-weighted-traffic-split"},
    "18": {"session": "22", "source_status": "OFFICIAL SOURCE LAB", "doc_status": "SOURCE-DERIVED / EXPANDED", "objective": "Implement Transactional Outbox and Idempotency Keys.", "problem": "Saving to DB and sending to Kafka in the same method risks Dual-Write inconsistency if Kafka fails.", "arch_before": "Dual-write risk in Order Service.", "arch_after": "Order saved with Outbox event in same DB transaction. Idempotency enforced in Payment.", "concepts": "Transactional Outbox, Idempotent Consumer, Dual-Write Problem.", "prereq": "Lab 17.", "tasks": "1. Add Outbox table.\n2. Save event to DB.\n3. Add scheduler to poll Outbox.\n4. Add idempotency check in Payment.", "config": "`@Scheduled` for outbox polling.", "files": "`order-service`, `payment-service`", "acceptance": "Kafka messages reliably delivered exactly-once (effectively) without dual-write risk.", "verify": "Simulate Kafka crash during order creation.", "expect": "Order saved, Outbox event stored, polled when Kafka returns.", "failures": "Polling race conditions in multi-instance setup.", "troubleshoot": "Use ShedLock or Debezium for production outbox implementations.", "arch_impact": "Guarantees reliable messaging.", "relation": "Fixes design flaw in Lab 10A.", "evidence": "Official document missing locally; reconstructed and expanded from curriculum map / reference implementation.", "commit": "session-22: add-outbox-pattern-and-idempotency-keys"},
    "19": {"session": "23", "source_status": "OFFICIAL SOURCE LAB", "doc_status": "SOURCE-DERIVED / EXPANDED", "objective": "Perform Load and Stress Testing using k6.", "problem": "System performance under extreme load is unknown.", "arch_before": "Untested scaling limits.", "arch_after": "k6 scripts establish baseline performance metrics.", "concepts": "Load Testing, Stress Testing, Smoke Testing, Virtual Users (VUs).", "prereq": "Lab 18.", "tasks": "1. Write smoke-test.js.\n2. Write stress-test.js.\n3. Document bottleneck findings.", "config": "k6 VU and duration thresholds.", "files": "`k6/`", "acceptance": "k6 executes and generates performance report.", "verify": "`k6 run stress-test.js`.", "expect": "Metrics output to console.", "failures": "k6 crashes host machine due to excessive VUs.", "troubleshoot": "Scale down VUs or run k6 from a dedicated testing machine.", "arch_impact": "Validates system non-functional requirements.", "relation": "Final implementation lab.", "evidence": "Official document missing locally; reconstructed and expanded from curriculum map / reference implementation.", "commit": "session-23: add-k6-stress-test-and-bottleneck-findings"}
}

for lab_id, data in labs_data.items():
    folder = os.path.join("docs/labs", f"lab-{lab_id}")
    readme_path = os.path.join(folder, "README.md")
    
    content = f"""# Lab {lab_id.upper()} — Session {data['session']}

## Documentation Classification
* **Source Status:** {data['source_status']}
* **Training Documentation:** {data['doc_status']}

## 1. Exact Objective
{data['objective']}

## 2. Problem Being Solved
{data['problem']}

## 3. Architecture
* **Before the lab:** {data['arch_before']}
* **After the lab:** {data['arch_after']}
* **Architectural Impact:** {data['arch_impact']}

## 4. Concepts Explained
{data['concepts']}

## 5. Prerequisites
{data['prereq']}

## 6. Precise Implementation Tasks
{data['tasks']}

## 7. Important Configuration
{data['config']}

## 8. Expected Files/Components
{data['files']}

## 9. Acceptance Criteria
{data['acceptance']}

## 10. Verification Commands/Tests
{data['verify']}

## 11. Expected Behavior
{data['expect']}

## 12. Common Failure Modes & Troubleshooting
* **Failure Mode:** {data['failures']}
* **Troubleshooting Guidance:** {data['troubleshoot']}

## 13. Relationship to Curriculum
* **Context:** {data['relation']}
* **Source Evidence:** {data['evidence']}
* **Related Commit(s):** `{data['commit']}`
"""
    with open(readme_path, "w", encoding="utf-8") as f:
        f.write(content)

print("Regenerated 23 enriched lab READMEs.")
